### ISSUE TITLE
Toggle visibility from external link?

### ISSUE THREAD

**Issue by sixtyseven-multimedia** [philipbeel/contactable#20]
Hi from Germany,
first of all thank you for your nice plugin. I try to achieve toggling  the form by an external link, like this:

```
    // open and close feedback
    $('.feedback').on('click',function(e) {
        e.preventDefault();
        if($('#contactable-overlay').css('display') == 'block'){
            //is open, close it
            $('#contactable-contactForm').animate({"marginLeft": "-=390px"}, "4000");
            $('#contactable-inner').animate({"marginLeft": "-=387px"}, "4000").animate({"marginLeft": "+=5px"}, "2000");
            $('#contactable-overlay').css({display: 'none'});
        } else {
            // is close, open it
            $('#contactable-overlay').css({display: 'block'});
            $('#contactable-inner').animate({"marginLeft": "-=5px"}, "2000");
            $('#contactable-contactForm').animate({"marginLeft": "-=0px"}, "2000");
            $('#contactable-inner').animate({"marginLeft": "+=387px"}, "4000");
            $('#contactable-contactForm').animate({"marginLeft": "+=390px"}, "4000");   
        }
    });
```

Does not properly work for me. Do you have any advice how to toggle visibility of the form from anywhere on the page? Thank you for your help!

**Comment by philipbeel** [comment]
This seems like a monkey patch. What would you expect the link to do when the form was completed?The current implementation moved the link off the screen. We would need to nail this down before any work to be done.

**Comment by BN83** [comment]
Whilst this might not be supported anymore, I'd like this function too. I have contactable in a button on the side, however I also mention the form in the website text so saying "click here to open the contact form" would be handy rather than saying "click the contact button on the right hand side"
