### ISSUE TITLE
No "Sender"

### ISSUE THREAD

**Issue by greenskyes** [philipbeel/contactable#21]
Thank you very much for such nice plug-in. It works propertly! I have only one question: How can I apply an information about sender? For example, I use this form on my website and when anyone send me a massage from contact form, I get an E-Mail from "nobody". How can I apply this information?

**Comment by philipbeel** [comment]
Because the plugin uses php mail() it does not provide the sender out of the box, However, it appear to be possible using additional headers:

**Comment by greenskyes** [comment]
Thank you very much for your Feedback,

it works!

$headers   = array();
$headers .= "MIME-Version: 1.0" . "\r\n";
$headers .= "Content-type: text/html; charset=iso-8859-1" . "\r\n";
$headers .= "From: Message from Website" . "\r\n";
$headers .= "Reply-To: {$emailAddr}" . "\r\n";
