### ISSUE TITLE
jQuery.fn.toggle is deprecated

### ISSUE THREAD

**Issue by recxjdv** [philipbeel/contactable#22]
Currently contactable requires the use of jQuery migrate if you're using the current versions of jQuery. The browser console in chrome reports the following error (when you use migrate):

```
JQMIGRATE: jQuery.fn.toggle(handler, handler...) is deprecated
```

It appears related to the following code:

```javascript
// Toggle the form visibility
jQuery.fn.toggleClick = function() {
	var functions = arguments, iteration = 0
	return this.click(function() {
		functions[iteration].apply(this, arguments)
		iteration = (iteration + 1) % functions.length
	})
}
```

**Comment by pbeel** [comment]
It should be pretty straight forward to substitute this for an alternative method.
